function turnGreen1() {document.getElementById('turnGreen1').style.color = 'green'; document.getElementById('turnGreen1').style.fontWeight = 'bold';}
function turnGreen2() {document.getElementById('turnGreen2').style.color = 'green'; document.getElementById('turnGreen2').style.fontWeight = 'bold';}
function turnGreen3() {document.getElementById('turnGreen3').style.color = 'green'; document.getElementById('turnGreen3').style.fontWeight = 'bold';}
function turnGreen4() {document.getElementById('turnGreen4').style.color = 'green'; document.getElementById('turnGreen4').style.fontWeight = 'bold';}
function turnGreen5() {document.getElementById('turnGreen5').style.color = 'green'; document.getElementById('turnGreen5').style.fontWeight = 'bold';}
function turnGreen6() {document.getElementById('turnGreen6').style.color = 'green'; document.getElementById('turnGreen6').style.fontWeight = 'bold';}
function turnGreen7() {document.getElementById('turnGreen7').style.color = 'green'; document.getElementById('turnGreen7').style.fontWeight = 'bold';}
function turnGreen8() {document.getElementById('turnGreen8').style.color = 'green'; document.getElementById('turnGreen8').style.fontWeight = 'bold';}
function turnGreen9() {document.getElementById('turnGreen9').style.color = 'green'; document.getElementById('turnGreen9').style.fontWeight = 'bold';}
function turnGreen10() {document.getElementById('turnGreen10').style.color = 'green'; document.getElementById('turnGreen10').style.fontWeight = 'bold';}

function turnGreen11() {document.getElementById('turnGreen11').style.color = 'green'; document.getElementById('turnGreen11').style.fontWeight = 'bold';}
function turnGreen12() {document.getElementById('turnGreen12').style.color = 'green'; document.getElementById('turnGreen12').style.fontWeight = 'bold';}
function turnGreen13() {document.getElementById('turnGreen13').style.color = 'green'; document.getElementById('turnGreen13').style.fontWeight = 'bold';}
function turnGreen14() {document.getElementById('turnGreen14').style.color = 'green'; document.getElementById('turnGreen14').style.fontWeight = 'bold';}
function turnGreen15() {document.getElementById('turnGreen15').style.color = 'green'; document.getElementById('turnGreen15').style.fontWeight = 'bold';}
function turnGreen16() {document.getElementById('turnGreen16').style.color = 'green'; document.getElementById('turnGreen16').style.fontWeight = 'bold';}
function turnGreen17() {document.getElementById('turnGreen17').style.color = 'green'; document.getElementById('turnGreen17').style.fontWeight = 'bold';}
function turnGreen18() {document.getElementById('turnGreen18').style.color = 'green'; document.getElementById('turnGreen18').style.fontWeight = 'bold';}
function turnGreen19() {document.getElementById('turnGreen19').style.color = 'green'; document.getElementById('turnGreen19').style.fontWeight = 'bold';}
function turnGreen20() {document.getElementById('turnGreen20').style.color = 'green'; document.getElementById('turnGreen20').style.fontWeight = 'bold';}

function turnGreen21() {document.getElementById('turnGreen21').style.color = 'green'; document.getElementById('turnGreen21').style.fontWeight = 'bold';}
function turnGreen22() {document.getElementById('turnGreen22').style.color = 'green'; document.getElementById('turnGreen22').style.fontWeight = 'bold';}
function turnGreen23() {document.getElementById('turnGreen23').style.color = 'green'; document.getElementById('turnGreen23').style.fontWeight = 'bold';}
function turnGreen24() {document.getElementById('turnGreen24').style.color = 'green'; document.getElementById('turnGreen24').style.fontWeight = 'bold';}
function turnGreen25() {document.getElementById('turnGreen25').style.color = 'green'; document.getElementById('turnGreen25').style.fontWeight = 'bold';}
function turnGreen26() {document.getElementById('turnGreen26').style.color = 'green'; document.getElementById('turnGreen26').style.fontWeight = 'bold';}
function turnGreen27() {document.getElementById('turnGreen27').style.color = 'green'; document.getElementById('turnGreen27').style.fontWeight = 'bold';}
function turnGreen28() {document.getElementById('turnGreen28').style.color = 'green'; document.getElementById('turnGreen28').style.fontWeight = 'bold';}
function turnGreen29() {document.getElementById('turnGreen29').style.color = 'green'; document.getElementById('turnGreen29').style.fontWeight = 'bold';}
function turnGreen30() {document.getElementById('turnGreen30').style.color = 'green'; document.getElementById('turnGreen30').style.fontWeight = 'bold';}

function turnGreen31() {document.getElementById('turnGreen31').style.color = 'green'; document.getElementById('turnGreen31').style.fontWeight = 'bold';}
function turnGreen32() {document.getElementById('turnGreen32').style.color = 'green'; document.getElementById('turnGreen32').style.fontWeight = 'bold';}
function turnGreen33() {document.getElementById('turnGreen33').style.color = 'green'; document.getElementById('turnGreen33').style.fontWeight = 'bold';}
function turnGreen34() {document.getElementById('turnGreen34').style.color = 'green'; document.getElementById('turnGreen34').style.fontWeight = 'bold';}
function turnGreen35() {document.getElementById('turnGreen35').style.color = 'green'; document.getElementById('turnGreen35').style.fontWeight = 'bold';}
function turnGreen36() {document.getElementById('turnGreen36').style.color = 'green'; document.getElementById('turnGreen36').style.fontWeight = 'bold';}
function turnGreen37() {document.getElementById('turnGreen37').style.color = 'green'; document.getElementById('turnGreen37').style.fontWeight = 'bold';}
function turnGreen38() {document.getElementById('turnGreen38').style.color = 'green'; document.getElementById('turnGreen38').style.fontWeight = 'bold';}
function turnGreen39() {document.getElementById('turnGreen39').style.color = 'green'; document.getElementById('turnGreen39').style.fontWeight = 'bold';}
function turnGreen40() {document.getElementById('turnGreen40').style.color = 'green'; document.getElementById('turnGreen40').style.fontWeight = 'bold';}

function turnGreen41() {document.getElementById('turnGreen41').style.color = 'green'; document.getElementById('turnGreen41').style.fontWeight = 'bold';}
function turnGreen42() {document.getElementById('turnGreen42').style.color = 'green'; document.getElementById('turnGreen42').style.fontWeight = 'bold';}
function turnGreen43() {document.getElementById('turnGreen43').style.color = 'green'; document.getElementById('turnGreen43').style.fontWeight = 'bold';}
function turnGreen44() {document.getElementById('turnGreen44').style.color = 'green'; document.getElementById('turnGreen44').style.fontWeight = 'bold';}
function turnGreen45() {document.getElementById('turnGreen45').style.color = 'green'; document.getElementById('turnGreen45').style.fontWeight = 'bold';}
function turnGreen46() {document.getElementById('turnGreen46').style.color = 'green'; document.getElementById('turnGreen46').style.fontWeight = 'bold';}
function turnGreen47() {document.getElementById('turnGreen47').style.color = 'green'; document.getElementById('turnGreen47').style.fontWeight = 'bold';}
function turnGreen48() {document.getElementById('turnGreen48').style.color = 'green'; document.getElementById('turnGreen48').style.fontWeight = 'bold';}
function turnGreen49() {document.getElementById('turnGreen49').style.color = 'green'; document.getElementById('turnGreen49').style.fontWeight = 'bold';}
function turnGreen50() {document.getElementById('turnGreen50').style.color = 'green'; document.getElementById('turnGreen50').style.fontWeight = 'bold';}

function turnGreen51() {document.getElementById('turnGreen51').style.color = 'green'; document.getElementById('turnGreen51').style.fontWeight = 'bold';}
function turnGreen52() {document.getElementById('turnGreen52').style.color = 'green'; document.getElementById('turnGreen52').style.fontWeight = 'bold';}
function turnGreen53() {document.getElementById('turnGreen53').style.color = 'green'; document.getElementById('turnGreen53').style.fontWeight = 'bold';}
function turnGreen54() {document.getElementById('turnGreen54').style.color = 'green'; document.getElementById('turnGreen54').style.fontWeight = 'bold';}
function turnGreen55() {document.getElementById('turnGreen55').style.color = 'green'; document.getElementById('turnGreen55').style.fontWeight = 'bold';}
function turnGreen56() {document.getElementById('turnGreen56').style.color = 'green'; document.getElementById('turnGreen56').style.fontWeight = 'bold';}
function turnGreen57() {document.getElementById('turnGreen57').style.color = 'green'; document.getElementById('turnGreen57').style.fontWeight = 'bold';}
function turnGreen58() {document.getElementById('turnGreen58').style.color = 'green'; document.getElementById('turnGreen58').style.fontWeight = 'bold';}
function turnGreen59() {document.getElementById('turnGreen59').style.color = 'green'; document.getElementById('turnGreen59').style.fontWeight = 'bold';}
function turnGreen60() {document.getElementById('turnGreen60').style.color = 'green'; document.getElementById('turnGreen60').style.fontWeight = 'bold';}

function turnGreen61() {document.getElementById('turnGreen61').style.color = 'green'; document.getElementById('turnGreen61').style.fontWeight = 'bold';}
function turnGreen62() {document.getElementById('turnGreen62').style.color = 'green'; document.getElementById('turnGreen62').style.fontWeight = 'bold';}
function turnGreen63() {document.getElementById('turnGreen63').style.color = 'green'; document.getElementById('turnGreen63').style.fontWeight = 'bold';}
function turnGreen64() {document.getElementById('turnGreen64').style.color = 'green'; document.getElementById('turnGreen64').style.fontWeight = 'bold';}
function turnGreen65() {document.getElementById('turnGreen65').style.color = 'green'; document.getElementById('turnGreen65').style.fontWeight = 'bold';}
function turnGreen66() {document.getElementById('turnGreen66').style.color = 'green'; document.getElementById('turnGreen66').style.fontWeight = 'bold';}
function turnGreen67() {document.getElementById('turnGreen67').style.color = 'green'; document.getElementById('turnGreen67').style.fontWeight = 'bold';}
function turnGreen68() {document.getElementById('turnGreen68').style.color = 'green'; document.getElementById('turnGreen68').style.fontWeight = 'bold';}
function turnGreen69() {document.getElementById('turnGreen69').style.color = 'green'; document.getElementById('turnGreen69').style.fontWeight = 'bold';}
function turnGreen70() {document.getElementById('turnGreen70').style.color = 'green'; document.getElementById('turnGreen70').style.fontWeight = 'bold';}

function turnGreen71() {document.getElementById('turnGreen71').style.color = 'green'; document.getElementById('turnGreen71').style.fontWeight = 'bold';}
function turnGreen72() {document.getElementById('turnGreen72').style.color = 'green'; document.getElementById('turnGreen72').style.fontWeight = 'bold';}
function turnGreen73() {document.getElementById('turnGreen73').style.color = 'green'; document.getElementById('turnGreen73').style.fontWeight = 'bold';}
function turnGreen74() {document.getElementById('turnGreen74').style.color = 'green'; document.getElementById('turnGreen74').style.fontWeight = 'bold';}
function turnGreen75() {document.getElementById('turnGreen75').style.color = 'green'; document.getElementById('turnGreen75').style.fontWeight = 'bold';}
function turnGreen76() {document.getElementById('turnGreen76').style.color = 'green'; document.getElementById('turnGreen76').style.fontWeight = 'bold';}
function turnGreen77() {document.getElementById('turnGreen77').style.color = 'green'; document.getElementById('turnGreen77').style.fontWeight = 'bold';}
function turnGreen78() {document.getElementById('turnGreen78').style.color = 'green'; document.getElementById('turnGreen78').style.fontWeight = 'bold';}
function turnGreen79() {document.getElementById('turnGreen79').style.color = 'green'; document.getElementById('turnGreen79').style.fontWeight = 'bold';}
function turnGreen80() {document.getElementById('turnGreen80').style.color = 'green'; document.getElementById('turnGreen80').style.fontWeight = 'bold';}

function turnGreen81() {document.getElementById('turnGreen81').style.color = 'green'; document.getElementById('turnGreen81').style.fontWeight = 'bold';}
function turnGreen82() {document.getElementById('turnGreen82').style.color = 'green'; document.getElementById('turnGreen82').style.fontWeight = 'bold';}
function turnGreen83() {document.getElementById('turnGreen83').style.color = 'green'; document.getElementById('turnGreen83').style.fontWeight = 'bold';}
function turnGreen84() {document.getElementById('turnGreen84').style.color = 'green'; document.getElementById('turnGreen84').style.fontWeight = 'bold';}
function turnGreen85() {document.getElementById('turnGreen85').style.color = 'green'; document.getElementById('turnGreen85').style.fontWeight = 'bold';}
function turnGreen86() {document.getElementById('turnGreen86').style.color = 'green'; document.getElementById('turnGreen86').style.fontWeight = 'bold';}
function turnGreen87() {document.getElementById('turnGreen87').style.color = 'green'; document.getElementById('turnGreen87').style.fontWeight = 'bold';}
function turnGreen88() {document.getElementById('turnGreen88').style.color = 'green'; document.getElementById('turnGreen88').style.fontWeight = 'bold';}
function turnGreen89() {document.getElementById('turnGreen89').style.color = 'green'; document.getElementById('turnGreen89').style.fontWeight = 'bold';}
function turnGreen90() {document.getElementById('turnGreen90').style.color = 'green'; document.getElementById('turnGreen90').style.fontWeight = 'bold';}

function turnGreen91() {document.getElementById('turnGreen91').style.color = 'green'; document.getElementById('turnGreen91').style.fontWeight = 'bold';}
function turnGreen92() {document.getElementById('turnGreen92').style.color = 'green'; document.getElementById('turnGreen92').style.fontWeight = 'bold';}
function turnGreen93() {document.getElementById('turnGreen93').style.color = 'green'; document.getElementById('turnGreen93').style.fontWeight = 'bold';}
function turnGreen94() {document.getElementById('turnGreen94').style.color = 'green'; document.getElementById('turnGreen94').style.fontWeight = 'bold';}
function turnGreen95() {document.getElementById('turnGreen95').style.color = 'green'; document.getElementById('turnGreen95').style.fontWeight = 'bold';}
function turnGreen96() {document.getElementById('turnGreen96').style.color = 'green'; document.getElementById('turnGreen96').style.fontWeight = 'bold';}
function turnGreen97() {document.getElementById('turnGreen97').style.color = 'green'; document.getElementById('turnGreen97').style.fontWeight = 'bold';}
function turnGreen98() {document.getElementById('turnGreen98').style.color = 'green'; document.getElementById('turnGreen98').style.fontWeight = 'bold';}
function turnGreen99() {document.getElementById('turnGreen99').style.color = 'green'; document.getElementById('turnGreen99').style.fontWeight = 'bold';}
function turnGreen100() {document.getElementById('turnGreen100').style.color = 'green'; document.getElementById('turnGreen100').style.fontWeight = 'bold';}